### ISSUE TITLE
100% CPU usage during idle

### ISSUE THREAD

**Issue by theronic** [comnik/declarative-dataflow#51]
Not sure if this is timely related, websockets or something about polling, but I'm seeing release executable using 100% CPU during idle. Is this expected?

Probably [this loop](https://github.com/comnik/declarative-dataflow/blob/038d659d3ba2e131a0f85540786c5f95c97da47f/src/bin/server.rs#L204)

**Comment by comnik** [comment]
Right now, this is partly on us (that loop you point out), partly on Timely (https://github.com/TimelyDataflow/differential-dataflow/issues/114). A first step to rectifying this was event-driven scheduling landing in Timely, but some pieces are still missing. And it is not clear whether we even want it for large-scale, data-processing use cases.

If you increase the polling timeout here: https://github.com/comnik/declarative-dataflow/blob/038d659d3ba2e131a0f85540786c5f95c97da47f/src/bin/server.rs#L222 that should get it down quite a bit, but I'm not sure whether that has any adverse effects on the rest of the system.

**Comment by comnik** [comment]
Right now *I think* we could do inputs completely blocking, because we always step the worker to catch up with all inputs before continuing the event loop. But that is something we want to keep flexible.

**Comment by theronic** [comment]
Understandably, dedicated DF nodes could peg at 100%, but if adoption is a priority, then it seems worthwhile to be able to run DF (perhaps in debug mode) against blocking channels so it doesn't use up one of my eight cores. Since mutations arrive via evented websockets, it seems that could wake up the poll thread. For distributed replication, maybe a layer of crossbeam-channel indirection could feed into the main loop?

**Comment by comnik** [comment]
Yeah, I agree. Does the polling timeout workaround help? With superficial testing I don't notice any immediate problems.

Running with a blocking input source for single-worker, development mode would be a helpful  feature. I tried it just now and it stalls sometimes, because the command-sequencing dataflow is not taken into consideration when the server decides, whether more work is needed to process all inputs. Fixing that shouldn't be too hard, but needs a bit of work.

**Comment by comnik** [comment]
Update: server now comes with a "blocking" compile-time feature flag. Another potential problem there is sources, which is why we now have some scheduling logic (https://github.com/comnik/declarative-dataflow/commit/1a393c4513f93521a43cb8979fe0af266f5eac45).

That has to be integrated and the sequencer dataflow has to be probed.

**Comment by comnik** [comment]
Fixed, now that https://github.com/TimelyDataflow/timely-dataflow/pull/268 landed in Timely master.
